language: ruby
cache:
  bundler: true
sudo: false
rvm:
  - 2.2.4
services:
  - elasticsearch
before_script:
  - sleep 10
  - RAILS_ENV=test bundle exec rails db:create db:schema:load
  - rake searchkick:reindex:all
script:
  - bundle exec rspec
